const { v4: uuidv4 } = require('uuid');
const store = require('../data/store');

/**
 * Reusable Unified Workflow Engine for NEXUS AI
 */
class WorkflowEngine {
  /**
   * Create a new workflow based on structured AI output
   */
  createWorkflowFromIntake(aiResult, creator) {
    const wfId = `wf_${uuidv4().substring(0, 8)}`;
    const now = new Date().toISOString();

    let initialStatus = 'in_progress';
    let currentStep = 'Processing';
    let steps = [];
    let approvals = [];
    let tasks = [];

    const wfType = aiResult.workflow_type || 'approval';

    // Build specific steps, approvals and initial tasks according to Workflow Architecture
    if (wfType === 'approval') {
      initialStatus = 'pending_approval';
      currentStep = 'Manager Approval';
      steps = [
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'AI Intake & Verification', status: 'completed', completedAt: now, actor: 'Central AI Engine' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Manager Approval', status: 'in_progress', completedAt: null, actor: 'Manager' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'IT / Procurement Fulfillment', status: 'pending', completedAt: null, actor: 'IT Support' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Delivery & Final Handover', status: 'pending', completedAt: null, actor: creator.name || 'Employee' }
      ];
      approvals = [
        {
          id: `app_${uuidv4().substring(0, 6)}`,
          stepName: 'Manager Approval',
          approverRole: 'Manager',
          approverName: 'Sarah Connor',
          status: 'pending',
          decision: null,
          comments: null,
          requestedAt: now
        }
      ];
    } else if (wfType === 'expense') {
      initialStatus = 'pending_approval';
      currentStep = 'Manager Approval';
      steps = [
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'AI Policy & Receipt Verification', status: 'completed', completedAt: now, actor: 'Central AI Engine' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Manager Approval', status: 'in_progress', completedAt: null, actor: 'Manager' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Finance Disbursement', status: 'pending', completedAt: null, actor: 'Finance' }
      ];
      approvals = [
        {
          id: `app_${uuidv4().substring(0, 6)}`,
          stepName: 'Manager Approval',
          approverRole: 'Manager',
          approverName: 'Sarah Connor',
          status: 'pending',
          decision: null,
          comments: null,
          requestedAt: now
        }
      ];
    } else if (wfType === 'onboarding') {
      initialStatus = 'in_progress';
      currentStep = 'IT Provisioning & Workspace Setup';
      steps = [
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Candidate Profile & HR Compliance', status: 'completed', completedAt: now, actor: creator.name || 'HR Team' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'IT Provisioning & Workspace Setup', status: 'in_progress', completedAt: null, actor: 'IT Support' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Team Introduction & Mentorship', status: 'pending', completedAt: null, actor: 'Manager' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'First-Week Milestone Review', status: 'pending', completedAt: null, actor: 'HR Operations' }
      ];
    } else if (wfType === 'helpdesk') {
      initialStatus = 'in_progress';
      currentStep = 'IT Rapid Resolution';
      steps = [
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'AI Incident Triage & SLA Priority Tagging', status: 'completed', completedAt: now, actor: 'Central AI Engine' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'IT Rapid Resolution', status: 'in_progress', completedAt: null, actor: 'Alex Rivera (IT)' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Incident Post-Mortem & Close', status: 'pending', completedAt: null, actor: 'Alex Rivera (IT)' }
      ];
    } else if (wfType === 'meetingops') {
      initialStatus = 'in_progress';
      currentStep = 'Action Items in Execution';
      steps = [
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Transcript Ingestion & Entity Parsing', status: 'completed', completedAt: now, actor: 'Central AI Engine' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Action Items in Execution', status: 'in_progress', completedAt: null, actor: 'Assigned Owners' },
        { id: `step_${uuidv4().substring(0, 6)}`, name: 'Sprint Review Verification', status: 'pending', completedAt: null, actor: creator.name || 'Manager' }
      ];
    }

    // Populate Tasks generated by AI
    if (aiResult.tasks && Array.isArray(aiResult.tasks)) {
      tasks = aiResult.tasks.map((t, idx) => {
        let dueDate = t.dueDate;
        if (!dueDate) {
          if (t.dueInMinutes) dueDate = new Date(Date.now() + 1000 * 60 * t.dueInMinutes).toISOString();
          else if (t.dueInHours) dueDate = new Date(Date.now() + 3600000 * t.dueInHours).toISOString();
          else dueDate = new Date(Date.now() + 86400000 * (idx + 1)).toISOString();
        }
        return {
          id: `tsk_${uuidv4().substring(0, 6)}`,
          title: t.title,
          status: 'pending',
          assignee: t.assignee || 'Unassigned',
          role: t.role || 'Employee',
          dueDate
        };
      });
    }

    const workflow = {
      id: wfId,
      title: aiResult.title || 'Central Operations Workflow',
      type: wfType,
      status: initialStatus,
      priority: aiResult.priority || 'normal',
      creator: {
        id: creator.id || 'user_emp_1',
        name: creator.name || 'Omkar Dev',
        role: creator.role || 'Employee',
        department: creator.department || 'Engineering'
      },
      department: aiResult.extracted_data?.department || creator.department || 'Engineering',
      createdAt: now,
      updatedAt: now,
      ai_data: aiResult.extracted_data || {},
      current_step: currentStep,
      steps,
      approvals,
      tasks,
      activity_logs: [
        {
          timestamp: now,
          actor: creator.name || 'Employee',
          action: 'Initiated Workflow via AI Intake',
          details: aiResult.summary || 'AI structured analysis executed.'
        },
        {
          timestamp: now,
          actor: 'Central AI Engine',
          action: `Classified as ${wfType.toUpperCase()} with ${aiResult.priority || 'normal'} priority`,
          details: `Confidence: ${((aiResult.confidence || 0.95) * 100).toFixed(0)}%`
        }
      ]
    };

    // If critical helpdesk, generate instant monitor alert
    if (wfType === 'helpdesk' && aiResult.priority === 'critical') {
      store.addMonitorAlert({
        workflowId: wfId,
        workflowTitle: workflow.title,
        type: 'critical_sla_ticket',
        severity: 'critical',
        message: `Critical IT ticket created with ${aiResult.extracted_data?.sla_minutes || 20}m SLA limit. Immediate dispatch triggered.`,
        suggestedAction: 'Notify On-Duty IT technician'
      });
    }

    // Save to store
    store.saveWorkflow(workflow);
    return workflow;
  }

  /**
   * Process approval decision
   */
  processApproval(workflowId, approvalId, approverUser, decision, comments = '') {
    const wf = store.getWorkflowById(workflowId);
    if (!wf) throw new Error('Workflow not found');

    const approval = (wf.approvals || []).find(a => a.id === approvalId || a.status === 'pending');
    if (!approval) throw new Error('Pending approval not found');

    const now = new Date().toISOString();
    approval.status = decision === 'approved' ? 'approved' : 'rejected';
    approval.decision = decision;
    approval.comments = comments || (decision === 'approved' ? 'Approved according to department policy' : 'Rejected by manager');
    approval.decidedBy = approverUser.name || 'Manager';
    approval.decidedAt = now;

    // Log Activity
    wf.activity_logs.unshift({
      timestamp: now,
      actor: approverUser.name || 'Approver',
      action: `${decision === 'approved' ? 'APPROVED' : 'REJECTED'} workflow`,
      details: comments ? `Comments: ${comments}` : `Decision: ${decision}`
    });

    if (decision === 'approved') {
      if (wf.type === 'approval') {
        // Advance to step 3 (Fulfillment)
        const step2 = wf.steps.find(s => s.name === 'Manager Approval');
        if (step2) { step2.status = 'completed'; step2.completedAt = now; }
        
        const step3 = wf.steps.find(s => s.name.includes('Fulfillment') || s.name.includes('Procurement'));
        if (step3) { step3.status = 'in_progress'; }
        
        wf.current_step = step3 ? step3.name : 'Fulfillment in Progress';
        wf.status = 'in_progress';
      } else if (wf.type === 'expense') {
        // Advance to Finance Disbursement
        const step2 = wf.steps.find(s => s.name === 'Manager Approval');
        if (step2) { step2.status = 'completed'; step2.completedAt = now; }
        
        const step3 = wf.steps.find(s => s.name.includes('Finance'));
        if (step3) { step3.status = 'in_progress'; }
        
        wf.current_step = 'Finance Disbursement';
        wf.status = 'approved';
      } else {
        wf.status = 'in_progress';
      }
    } else {
      wf.status = 'rejected';
      wf.current_step = 'Rejected';
      const activeStep = wf.steps.find(s => s.status === 'in_progress');
      if (activeStep) activeStep.status = 'rejected';
    }

    wf.updatedAt = now;
    store.saveWorkflow(wf);
    return wf;
  }

  /**
   * Advance workflow to next step or complete it
   */
  advanceWorkflow(workflowId, user, nextStepName = null) {
    const wf = store.getWorkflowById(workflowId);
    if (!wf) throw new Error('Workflow not found');

    const now = new Date().toISOString();
    const currentActiveStepIndex = wf.steps.findIndex(s => s.status === 'in_progress');

    if (currentActiveStepIndex >= 0) {
      wf.steps[currentActiveStepIndex].status = 'completed';
      wf.steps[currentActiveStepIndex].completedAt = now;

      if (currentActiveStepIndex + 1 < wf.steps.length) {
        wf.steps[currentActiveStepIndex + 1].status = 'in_progress';
        wf.current_step = wf.steps[currentActiveStepIndex + 1].name;
        wf.status = 'in_progress';
      } else {
        wf.status = 'completed';
        wf.current_step = 'Completed';
      }
    } else {
      wf.status = 'completed';
      wf.current_step = 'Completed';
    }

    wf.activity_logs.unshift({
      timestamp: now,
      actor: user.name || 'System Operator',
      action: `Advanced workflow state to: ${wf.current_step}`,
      details: `Status: ${wf.status}`
    });

    wf.updatedAt = now;
    store.saveWorkflow(wf);
    return wf;
  }
}

module.exports = new WorkflowEngine();
